version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1    
    steps:
      - checkout
  test-pytest:
    docker:
      - image: circleci/python:3.6.1
    steps:
        - checkout
        - run: sudo pip install -U pytest bs4
        - run: pytest
workflows:
  version: 2
  test:
    jobs:
      - test-pytest